name: release linux gui binarie

on:
  release:
    types: [created]

jobs:
  release-binaries:
    name: release linux gui binarie
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.38
      with:
        pre_command: "apt update && apt install -y make libgtk-3-dev"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        binary_name: "twmd-GUI"
        goversion: "1.20"
        overwrite: true
        retry: 10
        build_command: "make linux-gui"
        md5sum: FALSE
        goos: linux
        goarch: amd64
